import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const ffvf = localFont({ src: "../../public/fonts/Final_Fantasy_IV_SNES.ttf" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ffvf.className}>{children}</body>
    </html>
  );
}
